spring:
  application:
    name: skilltracker-api-gateway
#ignore null fields in json
  jackson:
    default-property-inclusion: NON_NULL    
#secret key - should be encrypted
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437    