server:
  port: 8090
spring:
  application:
    name: skilltracker-security 
  main:
    allow-circular-references: true    

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    url: jdbc:mysql://localhost:3306/skilltracker?createDatabaseIfNotExist=true
    username: root
    password: pass@word1
    
# Hibernate ddl auto (create, create-drop, validate, update)    
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

# The SQL dialect makes Hibernate generate better SQL for the chosen database      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    config: 
      uri: http://localhost:8888
  management:
    security: 
      enabled: false       
#ignore null fields in json
  jackson:
    default-property-inclusion: NON_NULL       
# Eureka Discovery Server Configutations
eureka:
  instance:
    preferIpAddress: true      
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8761/eureka   
    registerWithEureka: true
    fetchRegistry: true         

management:
  endpoints:
    web:
      exposure:
        include: health,info
        
logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: TRACE        
    
#secret key - should be encrypted
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
#3 minutes validity
  #token: validity: 180000   